### ISSUE TITLE
Failed to build docker image....

### ISSUE THREAD

**Issue by kennethim** [inada-s/zdxsv#10]
Hi Shingo,
I found some errors when I run  docker-compose command in new release.
Btw, could you tell me how to "zdxsv initdb" with new env?

..............
24
go: finding github.com/kisielk/gotool v1.0.0
go: finding github.com/rogpeppe/go-internal v1.3.0
go: finding gopkg.in/errgo.v2 v2.1.0
go: finding golang.org/x/exp v0.0.0-20191002040644-a1355ae1e2c3
go: finding golang.org/x/mod v0.1.0
go: finding golang.org/x/image v0.0.0-20190802002840-cff245a6509b
go: finding golang.org/x/mobile v0.0.0-20190719004257-d2bd2a29d028
go: finding golang.org/x/lint v0.0.0-20190930215403-16217165b5de
go: finding honnef.co/go/tools v0.0.1-2019.2.3
go: finding rsc.io/binaryregexp v0.2.0
**can't load package: package github.com/BurntSushi/xgb/examples: build constraints exclude all Go files in /go/pkg/mod/github.com/!burnt!sushi/xgb@v0.0.0-20160522181843-27f122750802/examples
ERROR: Service 'login' failed to build: The command '/bin/sh -c go mod download  && go build ...' returned a non-zero code: 1**

**Comment by inada-s** [comment]
I fixed the issue. Please try latest version.

I replaced `config.toml` into `.env`.
This `.env` file is automatically used when you run `docker-compose` command.
Note that If you manually declare the environmental variables, the values of `.env` are overwritten by them.

**Comment by kennethim** [comment]
Hi Shingo,

Thanks for you help, it's ok now.
But the service of legacyweb and router cannot be started.

...............
Successfully built 28a913dcabf0
Successfully tagged zdxsv_dns:latest
Creating zdxsv_status_1       ... done
Creating zdxsv_battle_1 ...
Creating zdxsv_dns_1          ... done
Creating zdxsv_router_1 ...
Creating zdxsv_battle_1       ... done
Creating zdxsv_https-portal_1 ... done
Creating zdxsv_router_1       ... error
Creating zdxsv_legacyweb_1    ... error
Creating zdxsv_login_1        ... done
Creating zdxsv_web_1          ... done
ERROR: for zdxsv_legacyweb_1  Cannot start service legacyweb: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/entrypoint\": permission denied": unknown

ERROR: for zdxsv_router_1  Cannot start service router: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./router\": permission denied": unknown

ERROR: for legacyweb  Cannot start service legacyweb: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/entrypoint\": permission denied": unknown

ERROR: for router  Cannot start service router: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./router\": permission denied": unknown
ERROR: Encountered errors while bringing up the project.

**Comment by inada-s** [comment]
`make router` command builds the router binary and docker-image (it is not so beautiful operation).
`entrypoint` should have execute permission, but I don't know why this error happens.

All rebuilding docker images might help you.
```
docker-compose down
docker container prune
```

**Comment by kennethim** [comment]
I tried to rebuild all images, but the legacyweb still not started.
Do you have any idea to solve this issue?

**Comment by inada-s** [comment]
I have no idea. Please google and edit the Docker file..

https://stackoverflow.com/questions/38882654/docker-entrypoint-running-bash-script-gets-permission-denied

**Comment by kennethim** [comment]
I have fixed the issue, thank you very much.
